# Generated by Django 4.1.5 on 2023-02-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_node_citizen_nida_citizen_email_and_more'),
        ('authUser', '0002_alter_profile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.citizen'),
        ),
    ]
