# Generated by Django 4.1.5 on 2023-02-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='node',
            new_name='nida',
        ),
        migrations.AddField(
            model_name='citizen',
            name='email',
            field=models.EmailField(default='1', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='house_no',
            field=models.CharField(default='111332', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='phone_no',
            field=models.CharField(default='0635354535', max_length=200),
            preserve_default=False,
        ),
    ]
